"""统一浏览器执行器接口。"""

from typing import Protocol, runtime_checkable

from .models import (
    BrowserRunSpec, ClickCommand, CloseResult, CommandResult, ContentCommand,
    ContentResult, FillCommand, KeyboardCommand, NavigateCommand, PointerCommand,
    SelectCommand, SnapshotCommand, SnapshotResult, StartResult,
)


@runtime_checkable
class BrowserExecutor(Protocol):
    async def start(self, run: BrowserRunSpec) -> StartResult: ...
    async def navigate(self, command: NavigateCommand) -> CommandResult: ...
    async def snapshot(self, command: SnapshotCommand) -> SnapshotResult: ...
    async def click(self, command: ClickCommand) -> CommandResult: ...
    async def fill(self, command: FillCommand) -> CommandResult: ...
    async def select(self, command: SelectCommand) -> CommandResult: ...
    async def keyboard(self, command: KeyboardCommand) -> CommandResult: ...
    async def pointer(self, command: PointerCommand) -> CommandResult: ...
    async def content(self, command: ContentCommand) -> ContentResult: ...
    async def close(self, reason: str = "completed") -> CloseResult: ...

    @property
    def run_id(self) -> str | None: ...
