"""The kernel sees capabilities rather than application globals."""

from typing import AsyncIterator, Protocol
from .contracts import DispatchResult, ExecutionState, ToolCall


class ModelPort(Protocol):
    async def complete(self, state: ExecutionState, call_id: str, tools: list[dict]) -> dict: ...


class ToolPort(Protocol):
    def definitions(self) -> list[dict]: ...
    def display_name(self, call: ToolCall) -> str: ...
    def dispatch(self, state: ExecutionState, call: ToolCall) -> AsyncIterator[dict | DispatchResult]: ...
    async def recover(self, state: ExecutionState, call: ToolCall) -> DispatchResult: ...


class ControlPort(Protocol):
    def command(self) -> str | None: ...
    async def save(self, state: ExecutionState, boundary: str) -> None: ...


class ObserverPort(Protocol):
    async def event(self, state: ExecutionState, event: dict) -> None: ...
    async def model_usage(self, state: ExecutionState, fact: dict) -> None: ...
